name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas, exatamente na hora cheia

  workflow_dispatch:

  push:
    branches:
      - main # ou 'master', se for seu caso

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: EduardoLeao-system
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
